name: ISSUE LABEL

on:
  pull_request:
    types:
      - labeled

jobs:
  FUNCTION_REVIEW:
    if: github.event.label.name == '2.Function Review'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: branch name
        id: branch-name
        run: |
          echo ${{ github.sha }}
          echo ${{ github.head_ref }}
          echo ${{ github.repository }}
      - name: RUN CLONE
        id: clone
        run: |
          docker run \
          --rm \
          -i \
          -v e2e:/usr/src/app/e2e \
          -- privileged \
          clone yarn clone -r ${{ github.repository}} -C ${{ github.sha }} 
