name: ISSUE LABEL

on:
  pull_request:
    types:
      - labeled

jobs:
  FUNCTION_REVIEW:
    if: github.event.label.name == '2.Function Review'
    runs-on: 0261
    steps:
      - uses: actions/checkout@v2
      - name: branch name
        id: branch-name
        run: |
          echo ${{ github.sha }}
          echo ${{ github.head_ref }}
          echo ${{ github.repository }}
      - name: RUN CLONE
        id: clone
        run: |
          docker run --rm -i -v e2e-volume:/usr/src/app/e2e clone yarn clone -r ${{ github.repository}} -C ${{ github.sha }} -s center
      - name: RUN E2E
        id: e2e
        run: |
          docker run --rm -i -v e2e-volume:/usr/src/app/e2e runner yarn cypress run
      - name: RUN REPORT
        id: report
        run: |
          docker run --rm -i -v e2e-volume:/usr/src/app runner yarn report:merge
          docker run --rm -i -v e2e-volume:/usr/src/app runner yarn report:generate   
